# Generated by Django 6.0.3 on 2026-03-09 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('icon_color', models.CharField(default='text-primary', max_length=50)),
                ('icon_bg_color', models.CharField(default='bg-primary/10', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('individual_price', models.DecimalField(decimal_places=2, default=9.99, max_digits=10)),
                ('team_price', models.DecimalField(decimal_places=2, default=29.99, max_digits=10)),
                ('enterprise_price', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('individual_features', models.TextField(default='[]', help_text='JSON array of features')),
                ('team_features', models.TextField(default='[]', help_text='JSON array of features')),
                ('enterprise_features', models.TextField(default='[]', help_text='JSON array of features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('enterprise', 'Enterprise')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workforce.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'app')},
            },
        ),
    ]
