# Generated by Django 6.0.3 on 2026-03-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_remove_project_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
