# Generated by Django 6.0.3 on 2026-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_worklog_end_time_worklog_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
