# Generated by Django 4.2 on 2026-03-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_alter_app_id_alter_dailymetric_id_alter_leave_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='work_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='workforce.worklog'),
        ),
    ]
