# Generated by Django 4.2 on 2026-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_alter_query_work_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='work_log_date_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='work_log_description_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='work_log_end_time_snapshot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='work_log_start_time_snapshot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
