# Generated by Django 4.2 on 2026-04-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_publicholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('vacation', 'Work Trip'), ('permission', 'Permission'), ('other', 'Annual Leave'), ('work_related', 'Work-Related Absence')], max_length=20),
        ),
    ]
