# Generated by Django 4.2 on 2026-04-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_alter_leave_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_id', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('status', models.CharField(max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.CharField(default='admin', max_length=200)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
