# Generated by Django 4.2 on 2026-04-25 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0011_deletedlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('metric_name', models.CharField(max_length=200)),
                ('weight', models.IntegerField(help_text='Weight as percentage e.g. 20 for 20%')),
                ('description', models.TextField(help_text='What activities count toward this KPI')),
                ('perspective', models.CharField(default='Internal Process', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('report_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='workforce.staffprofile')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
