# Generated by Django 4.2 on 2026-08-04 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('workforce', '0012_departmentkpi_performancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='organizations.organization'),
        ),
    ]
