# Generated by Django 4.2 on 2026-08-04 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0013_staffprofile_department_fk_staffprofile_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sign_in_time', models.DateTimeField(blank=True, null=True)),
                ('sign_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sign_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sign_in_method', models.CharField(choices=[('geofence', 'Geofence'), ('manual', 'Manual'), ('biometric', 'Biometric')], default='geofence', max_length=20)),
                ('sign_out_time', models.DateTimeField(blank=True, null=True)),
                ('sign_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sign_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='present', max_length=20)),
                ('distance_from_office_m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='workforce.staffprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['staff', 'date'], name='attendance__staff_i_960a40_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance__date_61f2e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('staff', 'date')},
        ),
    ]
