# Generated by Django 4.2 on 2026-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_webauthn_and_field_clockin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
